### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by wiggitywhitney** [vfarcic/cncf-demo#10]
https://github.com/vfarcic/cncf-demo/blob/6392a939100acd578bf77fa97c40f6779ce3736c/manuscript/build-container-image/kbld.md?plain=1#L30

Why are we doing this?  I'm confused because this changes the tag locally but the deployment yaml still references the old tag

**Comment by vfarcic** [comment]
We're doing that for three reasons.
1. I could not figure out how to build an image with a specific tag.
2. We did not yet go through the part of defining apps. kbld modifies the manifests but, if there are (not yet) manifests to modify, we have a "chicken and egg" type of a problem.
3. We could come back to kbld later when we do figure out how to define apps but I did not figure out how to make kbld work with Kustomize and Helm (with ytt yes).
