### ISSUE TITLE
kbld image

### ISSUE THREAD

**Issue by vfarcic** [vfarcic/cncf-demo#4]
@wiggitywhitney Is there a way to specify the name of the image that will be built instead of the default `kbld`? Right now, the `kbld --file kbld/deployment.yaml` command in https://github.com/vfarcic/cncf-demo/blob/main/manuscript/build-container-image/kbld.md#do builds an image `kbld` instead of `cncf-demo`. I thought that we could specify it by adding `destination` section in https://github.com/vfarcic/cncf-demo/blob/main/kbld/deployment.yaml#L40 but that one insists on pushing the image to a registry and we do not yet have a registry in this part of the "story". Do you know any other way to specify the name of the image that should be built?

In the meantime, I added `docker image tag kbld:$TAG cncf-demo:$TAG` to https://github.com/vfarcic/cncf-demo/blob/main/manuscript/build-container-image/kbld.md as a workaround.

**Comment by wiggitywhitney** [comment]
https://kubernetes.slack.com/archives/CH8KCCKA5/p1670242460643359
